name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:    
  build:
    runs-on: ubuntu-latest         
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  deploy_staging:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - run: echo "test on staging"
        name: deploying to staging
        
  deploy_production:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - run: echo "ship it!"
        name: deploying to production
  
