name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:    
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest         
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: AppConfigurationExample
    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: AppConfigurationExample
#    - name: Test
#      run: dotnet test --no-build --verbosity normal -c Release
#      working-directory: AppConfigurationExample
    - name: publish
      run: dotnet publish --no-build -c Release
      working-directory: AppConfigurationExample
    - name: Display structure of dir
      run: ls -R
      working-directory: AppConfigurationExample
    - uses: actions/upload-artifact@v2
      with:
        name: drop
        path: ./AppConfigurationExample/bin/Release/netcoreapp3.1/publish
  
  deploy_staging:
    name: Deploy to staging environment
    needs: [build_and_test]
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: drop
      - name: Display structure of downloaded files
        run: ls -R
      - run: echo "test on staging"
        name: deploying to staging
        
  deploy_production:
    name: Deploy to production environment
    needs: [deploy_staging]
    environment: production
    runs-on: ubuntu-latest
    steps:
      - run: echo "ship it!"
        name: deploying to production
  
